#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\e[42m                 DELETE USER             \E[0m"
echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
read -p "   Username : " USERSSH

if [ -z $USERSSH ]; then
    echo -e "Username cannot be empty "
else
    if getent passwd $USERSSH >/dev/null 2>&1; then
        userdel $USERSSH >/dev/null 2>&1
        sed -i "/^### $USERSSH/d" /etc/ssh/.ssh.db
        echo -e "User $USERSSH was removed."
    else
        echo -e "Failure: User $USERSSH Not Exist."
    fi
fi
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
