#!/bin/bash
# =========================================
# Quick Setup | Script Setup Manager
# Edition : Stable Edition V1.0
# Auther  : NevermoreSSH
# (C) Copyright 2022
# =========================================
clear
MYIP=$(wget -qO- ipv4.icanhazip.com);
NUMBER_OF_CLIENTS=$(grep -c -E "^#& " "/etc/xray/config.json")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
                echo -e "---------------------------------------------------"
                echo -e "---------=[ Check XRAYS/Vless WS Config ]=---------"
                echo -e "---------------------------------------------------"
                echo ""
                echo "You have no existing clients!"
                clear
                exit 1
        fi

        echo -e "---------------------------------------------------"
        echo -e "---------=[ Check XRAYS/Vless WS Config ]=---------"
        echo -e "---------------------------------------------------"
        echo " Select the existing client to view the config"
        echo " Press CTRL+C to return"
		echo -e "---------------------------------------------------"
        echo "     No  Expired   User"
        grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') '
        until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
                if [[ ${CLIENT_NUMBER} == '1' ]]; then
                        read -rp "Select one client [1]: " CLIENT_NUMBER
                else
                        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
                fi
        done
clear
user=$(grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
CITY=$(cat /etc/xray/city)
NS=$(cat /etc/xray/dns)
uuid=$(grep "},{" /etc/xray/config.json | cut -b 11-46 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
hariini=`date -d "0 days" +"%Y-%m-%d"`
tls="$(cat ~/log-install.txt | grep -w "Vless TLS" | cut -d: -f2|sed 's/ //g')"
nontls="$(cat ~/log-install.txt | grep -w "Vless None TLS" | cut -d: -f2|sed 's/ //g')"

#xrayvless1="vless://${uuid}@${domain}:$tls?type=ws&encryption=none&security=tls&host=${domain}&path=/vless&allowInsecure=1&sni=${sni}#XRAY_VLESS_${user}"
#xrayvless2="vless://${uuid}@${domain}:$nontls?type=ws&encryption=none&security=none&host=${domain}&path=/vless#XRAY_VLESS_${user}"
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#XRAY_VLESS_${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#XRAY_VLESS_${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#XRAY_VLESS_${user}"
vlesslink4="vless://${uuid}@${domain}:80?path=http://tsel.me/worryfree&encryption=none&type=ws#XRAY_VLESS_${user}"

clear
#echo -e ""
#echo -e "======-XRAYS/VLESS-======"
#echo -e "Remarks     : ${user}"
#echo -e "IP/Host     : ${MYIP}"
#echo -e "Address     : ${domain}"
#echo -e "Port TLS    : $tls"
#echo -e "Port No TLS : $nontls"
#echo -e "User ID     : ${uuid}"
#echo -e "Encryption  : none"
#echo -e "Network     : ws"
#echo -e "Path        : /vless"
#echo -e "Multipath   : /yourpath (XrayCore Mod)"
#echo -e "Created     : $hariini"
#echo -e "Expired     : $exp"
#echo -e "========================="
#echo -e "Link TLS    : ${xrayvless1}"
#echo -e "========================="
#echo -e "Link No TLS : ${xrayvless2}"
#echo -e "========================="
#echo -e "Script Mod By NevermoreSSH"
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "\e[42m    Xray/Vless Account     \E[0m" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Remarks     : ${user}" | tee -a /etc/nevermoressh/user.log
echo -e "Domain      : ${domain}" | tee -a /etc/nevermoressh/user.log
echo -e "Host Slowdns: ${NS}" | tee -a /etc/nevermoressh/user.log
echo -e "Pub Key     : ${PUB}" | tee -a /etc/nevermoressh/user.log
#echo -e "Location    : $CITY" | tee -a /etc/nevermoressh/user.log
#echo -e "User Quota  : ${Quota} GB" | tee -a /etc/nevermoressh/user.log
echo -e "port TLS    : 443" | tee -a /etc/nevermoressh/user.log
echo -e "Port DNS    : 443, 53 " | tee -a /etc/nevermoressh/user.log
echo -e "Port NTLS   : 80, 8080, 2086" | tee -a /etc/nevermoressh/user.log
echo -e "User ID     : ${uuid}" | tee -a /etc/nevermoressh/user.log
echo -e "Encryption  : none" | tee -a /etc/nevermoressh/user.log
echo -e "Path TLS    : /vless " | tee -a /etc/nevermoressh/user.log
echo -e "ServiceName : vless-grpc" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Link TLS   : ${vlesslink1}" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Link NTLS  : ${vlesslink2}" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Link GRPC  : ${vlesslink3}" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
#echo -e "Link OPOK  : ${vlesslink4}" | tee -a /etc/nevermoressh/user.log
#echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Format OpenClash : https://${domain}:81/vless-$user.txt" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Expired On : $exp" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "" | tee -a /etc/nevermoressh/user.log
read -n 1 -s -r -p "Press any key to back on menu"
