#!/bin/bash
# =========================================
# Quick Setup | Script Setup Manager
# Edition : Stable Edition V1.0
# Auther  : NevermoreSSH
# (C) Copyright 2022
# =========================================
clear
MYIP=$(wget -qO- ipv4.icanhazip.com);
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/xray/config.json")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
                echo -e "---------------------------------------------------"
                echo -e "---------=[ Check XRAYS/Vmess WS Config ]=---------"
                echo -e "---------------------------------------------------"
                echo ""
                echo "You have no existing clients!"
                clear
                exit 1
        fi

        echo -e "---------------------------------------------------"
        echo -e "---------=[ Check XRAYS/Vmess WS Config ]=---------"
        echo -e "---------------------------------------------------"
        echo " Select the existing client to view the config"
        echo " Press CTRL+C to return"
		echo -e "---------------------------------------------------"
        echo "     No  Expired   User"
        grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') '
        until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
                if [[ ${CLIENT_NUMBER} == '1' ]]; then
                        read -rp "Select one client [1]: " CLIENT_NUMBER
                else
                        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
                fi
        done
user=$(grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
tls="$(cat ~/log-install.txt | grep -w "Vmess TLS" | cut -d: -f2|sed 's/ //g')"
nontls="$(cat ~/log-install.txt | grep -w "Vmess None TLS" | cut -d: -f2|sed 's/ //g')"
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
CITY=$(cat /etc/xray/city)
NS=$(cat /etc/xray/dns)
uuid=$(grep "},{" /etc/xray/config.json | cut -b 11-46 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
hariini=`date -d "0 days" +"%Y-%m-%d"`
vmess_base641=$( base64 -w 0 <<< $vmess_json1)
vmess_base642=$( base64 -w 0 <<< $vmess_json2)
#xrayv2ray1="vmess://$(base64 -w 0 /etc/xray/vmess-$user-tls.json)"
#xrayv2ray2="vmess://$(base64 -w 0 /etc/xray/vmess-$user-nontls.json)"
vmesslink1="vmess://$(echo $VMESS_WS | base64 -w 0)"
vmesslink2="vmess://$(echo $VMESS_NON_TLS | base64 -w 0)"
vmesslink3="vmess://$(echo $VMESS_GRPC | base64 -w 0)"
vmesslink4="vmess://$(echo $VMESS_OPOK | base64 -w 0)"
clear
#echo -e ""
#echo -e "======-XRAYS/VMESS-======"
#echo -e "Remarks     : ${user}"
#echo -e "IP/Host     : ${MYIP}"
#echo -e "Address     : ${domain}"
#echo -e "Port TLS    : ${tls}"
#echo -e "Port No TLS : ${nontls}"
#echo -e "User ID     : ${uuid}"
#echo -e "Alter ID    : 0"
#echo -e "Security    : auto"
#echo -e "Network     : ws"
#echo -e "Path        : /vmess"
#echo -e "Multipath   : /yourpath (XrayCore Mod)"
#echo -e "Created     : $hariini"
#echo -e "Expired     : $exp"
#echo -e "========================="
#echo -e "Link TLS    : ${xrayv2ray1}"
#echo -e "========================="
#echo -e "Link No TLS : ${xrayv2ray2}"
#echo -e "========================="
#echo -e "Script Mod By NevermoreSSH"
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "\e[42m    Xray/Vmess Account     \E[0m" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Remarks      : ${user}" | tee -a /etc/nevermoressh/user.log
echo -e "Domain       : ${domain}" | tee -a /etc/nevermoressh/user.log
echo -e "Host Slowdns : ${NS}" | tee -a /etc/nevermoressh/user.log
echo -e "Pub Key      : ${PUB}" | tee -a /etc/nevermoressh/user.log
#echo -e "Location     : $CITY" | tee -a /etc/nevermoressh/user.log
#echo -e "User Quota   : ${Quota} GB" | tee -a /etc/nevermoressh/user.log
echo -e "Port TLS     : 443" | tee -a /etc/nevermoressh/user.log
echo -e "Port NTLS    : 80, 8080, 2086" | tee -a /etc/nevermoressh/user.log
echo -e "Port DNS     : 443, 53 " | tee -a /etc/nevermoressh/user.log
echo -e "Port GRPC    : 443" | tee -a /etc/nevermoressh/user.log
echo -e "User ID      : ${uuid}" | tee -a /etc/nevermoressh/user.log
echo -e "AlterId      : 0" | tee -a /etc/nevermoressh/user.log
echo -e "Security     : auto" | tee -a /etc/nevermoressh/user.log
echo -e "Network      : WS or GRPC" | tee -a /etc/nevermoressh/user.log
echo -e "Path TLS     : (/multi path) " | tee -a /etc/nevermoressh/user.log
echo -e "Path NLS     : (/multi path) " | tee -a /etc/nevermoressh/user.log
#echo -e "Path Dynamic : CF-XRAY:http://bug.com " | tee -a /etc/nevermoressh/user.log
echo -e "ServiceName  : vmess-grpc" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Link TLS     : ${vmesslink1}" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Link NTLS    : ${vmesslink2}" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Link GRPC    : ${vmesslink3}" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
#echo -e "Link OPOK    : ${vmesslink4}" | tee -a /etc/nevermoressh/user.log
#echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Format OpenClash : https://${domain}:81/vmess-$user.txt" | tee -a /etc/nevermoressh/user.log
echo -e "\033[1;93m───────────────────────────\033[0m" | tee -a /etc/nevermoressh/user.log
echo -e "Expired On : $exp" | tee -a /etc/nevermoressh/user.log
echo -e "" | tee -a /etc/nevermoressh/user.log
read -n 1 -s -r -p "Press any key to back on menu"
